set_property PACKAGE_PIN T1 [get_ports hdmi_tx_clk_p]
set_property PACKAGE_PIN U1 [get_ports hdmi_tx_clk_n]
set_property PACKAGE_PIN W1 [get_ports hdmi_tx_p0]
set_property PACKAGE_PIN Y1 [get_ports hdmi_tx_n0]
set_property PACKAGE_PIN AA1 [get_ports hdmi_tx_p1]
set_property PACKAGE_PIN AB1 [get_ports hdmi_tx_n1]
set_property PACKAGE_PIN AB3 [get_ports hdmi_tx_p2]
set_property PACKAGE_PIN AB2 [get_ports hdmi_tx_n2]

set_property IOSTANDARD TMDS_33 [get_ports hdmi_tx_clk_p]
set_property IOSTANDARD TMDS_33 [get_ports hdmi_tx_clk_n]
set_property IOSTANDARD TMDS_33 [get_ports hdmi_tx_p0]
set_property IOSTANDARD TMDS_33 [get_ports hdmi_tx_n0]
set_property IOSTANDARD TMDS_33 [get_ports hdmi_tx_p1]
set_property IOSTANDARD TMDS_33 [get_ports hdmi_tx_n1]
set_property IOSTANDARD TMDS_33 [get_ports hdmi_tx_p2]
set_property IOSTANDARD TMDS_33 [get_ports hdmi_tx_n2]
